import unicorn from "eslint-plugin-unicorn";
import security from "eslint-plugin-security";
import esx from "eslint-plugin-es-x";
import jsdoc from "eslint-plugin-jsdoc";
import prettier from "eslint-plugin-prettier";
import prettierConfig from "eslint-config-prettier";

export default [
	{
		plugins: { unicorn, security, "es-x": esx, jsdoc, prettier },
		languageOptions: {
			ecmaVersion: 2017,
			sourceType: "module",
			globals: {
				// MediaWiki globals
				mw: "readonly",
				$: "readonly",
				OO: "readonly",
				// Browser globals (Wikimedia client enables browser env)
				window: "readonly",
				document: "readonly",
				console: "readonly",
				alert: "readonly",
				confirm: "readonly",
				prompt: "readonly",
				localStorage: "readonly",
				setTimeout: "readonly",
				clearTimeout: "readonly",
				setInterval: "readonly",
				clearInterval: "readonly",
				// ES2017 globals
				Atomics: "readonly",
				SharedArrayBuffer: "readonly"
			}
		},
		settings: { "es-x": { aggressive: true } },
		rules: {
			// Wikimedia common rules
			"array-bracket-spacing": ["error", "always"],
			"array-callback-return": "error",
			"block-scoped-var": "error",
			"block-spacing": "error",
			"brace-style": ["error", "1tbs"],
			"camelcase": ["error", { "properties": "always" }],
			"comma-dangle": ["error", "never"],
			"comma-spacing": ["error", { "before": false, "after": true }],
			"comma-style": ["error", "last"],
			"computed-property-spacing": ["error", "always"],
			"curly": ["error", "all"],
			"dot-location": ["error", "property"],
			"dot-notation": "error",
			"eol-last": "error",
			"eqeqeq": "error",
			"func-call-spacing": "error",
			"indent": ["error", "tab", { "SwitchCase": 1 }],
			"key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
			"keyword-spacing": "error",
			"linebreak-style": ["error", "unix"],
			"max-len": ["warn", { "code": 100, "tabWidth": 4, "ignorePattern": "^[\\s]*(//|<!--) (es|style)lint-.+", "ignoreUrls": true, "ignoreComments": false, "ignoreRegExpLiterals": true, "ignoreStrings": true, "ignoreTemplateLiterals": true }],
			"max-statements-per-line": ["error", { "max": 1 }],
			"new-cap": ["error", { "newIsCap": true, "capIsNew": false, "properties": true }],
			"new-parens": "error",
			"no-array-constructor": "error",
			"no-bitwise": "error",
			"no-caller": "error",
			"no-constant-binary-expression": "error",
			"no-constant-condition": ["error", { "checkLoops": false }],
			"no-empty": ["error", { "allowEmptyCatch": true }],
			"no-eval": "error",
			"no-extend-native": "error",
			"no-extra-bind": "error",
			"no-extra-label": "error",
			"no-floating-decimal": "error",
			"no-implicit-coercion": ["error", { "string": true, "boolean": false, "number": false }],
			"no-implicit-globals": "error",
			"no-label-var": "error",
			"no-loop-func": "error",
			"no-loss-of-precision": "error",
			"no-multi-spaces": "error",
			"no-multiple-empty-lines": ["error", { "max": 1, "maxBOF": 0, "maxEOF": 0 }],
			"no-new": "error",
			"no-new-func": "error",
			"no-new-object": "error",
			"no-new-wrappers": "error",
			"no-nonoctal-decimal-escape": "error",
			"no-octal-escape": "error",
			"no-proto": "error",
			"no-prototype-builtins": "error",
			"no-return-assign": "error",
			"no-script-url": "error",
			"no-self-compare": "error",
			"no-sequences": "error",
			"no-shadow": ["error", { "hoist": "all" }],
			"no-shadow-restricted-names": "error",
			"no-tabs": ["error", { "allowIndentationTabs": true }],
			"no-throw-literal": "error",
			"no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-underscore-dangle": "error",
			"no-unmodified-loop-condition": "error",
			"no-unneeded-ternary": ["error", { "defaultAssignment": false }],
			"no-unreachable-loop": "error",
			"no-unused-expressions": "error",
			"no-use-before-define": ["error", "nofunc"],
			"no-useless-call": "error",
			"no-useless-concat": "error",
			"no-void": "error",
			"no-whitespace-before-property": "error",
			"no-with": "error",
			"object-curly-spacing": ["error", "always"],
			"operator-linebreak": ["error", "after"],
			"prefer-numeric-literals": "error",
			"prefer-regex-literals": "error",
			"quote-props": ["error", "as-needed"],
			"quotes": ["error", "single", { "avoidEscape": true }],
			"semi": ["error", "always"],
			"semi-spacing": ["error", { "before": false, "after": true }],
			"semi-style": ["error", "last"],
			"space-before-blocks": ["error", "always"],
			"space-before-function-paren": ["error", { "anonymous": "always", "named": "never" }],
			"space-in-parens": ["error", "always", { "exceptions": ["empty"] }],
			"space-infix-ops": "error",
			"space-unary-ops": ["error", { "words": true, "nonwords": false }],
			"spaced-comment": ["error", "always", { "exceptions": ["*", "!"], "block": { "balanced": true } }],
			"switch-colon-spacing": ["error", { "after": true, "before": false }],
			"unicode-bom": "error",
			"wrap-iife": "error",
			"yoda": ["error", "never"],

			// Common extras
			"security/detect-object-injection": "off",
			"unicorn/prefer-date-now": "error",
			"unicorn/prefer-string-slice": "error",
			"unicorn/throw-new-error": "error",

			// Client-specific rules (browser environment)
			"no-alert": "error",
			"no-console": "error",
			"no-implied-eval": "error",
			"unicorn/no-invalid-remove-event-listener": "error",
			"security/detect-non-literal-regexp": "off",
			"security/detect-unsafe-regex": "off",
			"security/detect-possible-timing-attacks": "off",

			// ES2017 language profile
			"arrow-parens": "error",
			"arrow-spacing": "error",
			"default-param-last": "error",
			"lines-between-class-members": "error",
			"no-constructor-return": "error",
			"no-misleading-character-class": "error",
			"no-new-require": "error",
			"no-promise-executor-return": "error",
			"no-useless-computed-key": "error",
			"template-curly-spacing": ["error", "always"],
			"no-var": "error",
			"prefer-const": "error",
			"prefer-arrow-callback": "error",
			"implicit-arrow-linebreak": "error",
			"arrow-body-style": "error",
			"unicorn/no-useless-promise-resolve-reject": "error",
			"unicorn/prefer-includes": "error",
			"es-x/no-restricted-syntax": "off",
			"es-x/no-symbol-prototype-description": "off",
			"es-x/no-resizable-and-growable-arraybuffers": "off",

			// ES2017 specific
			"no-await-in-loop": "error",
			"require-atomic-updates": "error",

			// Prettier integration
			"prettier/prettier": "error"
		}
	},
	// Prettier config to disable conflicting rules
	...prettierConfig
];
