import unicorn from "eslint-plugin-unicorn";
import security from "eslint-plugin-security";
import esx from "eslint-plugin-es-x";
import jsdoc from "eslint-plugin-jsdoc";
import stylistic from "@stylistic/eslint-plugin";
import json from "@eslint/json";
import markdown from "@eslint/markdown";

export default [
	{
		name: "rater/base",
		files: ["**/*.js"],
		plugins: { unicorn, security, "es-x": esx, jsdoc, "@stylistic": stylistic, "@stylistic/js": stylistic },
		languageOptions: {
			ecmaVersion: 2017,
			sourceType: "module",
			globals: {
				// MediaWiki globals
				mw: "readonly",
				$: "readonly",
				OO: "readonly",
				// Browser globals (Wikimedia client enables browser env)
				window: "readonly",
				document: "readonly",
				console: "readonly",
				alert: "readonly",
				confirm: "readonly",
				prompt: "readonly",
				localStorage: "readonly",
				setTimeout: "readonly",
				clearTimeout: "readonly",
				setInterval: "readonly",
				clearInterval: "readonly",
				// ES2017 globals
				Atomics: "readonly",
				SharedArrayBuffer: "readonly"
			}
		},
		settings: { "es-x": { aggressive: true } },
		linterOptions: { reportUnusedDisableDirectives: "warn" },
		ignores: ["!.*.*", ".*/*", "node_modules/*"],
			rules: {
			// Wikimedia common rules
				"@stylistic/array-bracket-spacing": ["error", "always"],
			"array-callback-return": "error",
			"block-scoped-var": "error",
				"@stylistic/block-spacing": "error",
				"@stylistic/brace-style": ["error", "1tbs"],
			"camelcase": ["error", { "properties": "always" }],
				"@stylistic/comma-dangle": ["error", "never"],
				"@stylistic/comma-spacing": ["error", { "before": false, "after": true }],
				"@stylistic/comma-style": ["error", "last"],
				"@stylistic/computed-property-spacing": ["error", "always"],
			"curly": ["error", "all"],
				"@stylistic/dot-location": ["error", "property"],
			"dot-notation": "error",
				"@stylistic/eol-last": "error",
			"eqeqeq": "error",
				"@stylistic/function-call-spacing": "error",
				"@stylistic/indent": ["error", "tab", { "SwitchCase": 1 }],
				"@stylistic/key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
				"@stylistic/keyword-spacing": "error",
				"@stylistic/linebreak-style": ["error", "unix"],
				"@stylistic/max-len": ["warn", { "code": 100, "tabWidth": 4, "ignorePattern": "^[\\s]*(//|<!--) (es|style)lint-.+", "ignoreUrls": true, "ignoreComments": false, "ignoreRegExpLiterals": true, "ignoreStrings": true, "ignoreTemplateLiterals": true }],
				"@stylistic/max-statements-per-line": ["error", { "max": 1 }],
			"new-cap": ["error", { "newIsCap": true, "capIsNew": false, "properties": true }],
				"@stylistic/new-parens": "error",
			"no-array-constructor": "error",
			"no-bitwise": "error",
			"no-caller": "error",
			"no-constant-binary-expression": "error",
			"no-constant-condition": ["error", { "checkLoops": false }],
			"no-empty": ["error", { "allowEmptyCatch": true }],
			"no-eval": "error",
			"no-extend-native": "error",
			"no-extra-bind": "error",
			"no-extra-label": "error",
				"@stylistic/no-floating-decimal": "error",
			"no-implicit-coercion": ["error", { "string": true, "boolean": false, "number": false }],
			"no-implicit-globals": "error",
			"no-label-var": "error",
			"no-loop-func": "error",
			"no-loss-of-precision": "error",
				"@stylistic/no-multi-spaces": "error",
				"@stylistic/no-multiple-empty-lines": ["error", { "max": 1, "maxBOF": 0, "maxEOF": 0 }],
			"no-new": "error",
			"no-new-func": "error",
			"no-new-object": "error",
			"no-new-wrappers": "error",
			"no-nonoctal-decimal-escape": "error",
			"no-octal-escape": "error",
			"no-proto": "error",
			"no-prototype-builtins": "error",
			"no-return-assign": "error",
			"no-script-url": "error",
			"no-self-compare": "error",
			"no-sequences": "error",
			"no-shadow": ["error", { "hoist": "all" }],
			"no-shadow-restricted-names": "error",
				"@stylistic/no-tabs": ["error", { "allowIndentationTabs": true }],
			"no-throw-literal": "error",
				"@stylistic/no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-underscore-dangle": "error",
			"no-unmodified-loop-condition": "error",
			"no-unneeded-ternary": ["error", { "defaultAssignment": false }],
			"no-unreachable-loop": "error",
			"no-unused-expressions": "error",
			"no-use-before-define": ["error", "nofunc"],
			"no-useless-call": "error",
			"no-useless-concat": "error",
			"no-void": "error",
				"@stylistic/no-whitespace-before-property": "error",
			"no-with": "error",
				"@stylistic/object-curly-spacing": ["error", "always"],
				"@stylistic/operator-linebreak": ["error", "after"],
			"prefer-numeric-literals": "error",
			"prefer-regex-literals": "error",
				"@stylistic/quote-props": ["error", "as-needed"],
				"@stylistic/quotes": ["error", "single", { "avoidEscape": true }],
				"@stylistic/semi": ["error", "always"],
				"@stylistic/semi-spacing": ["error", { "before": false, "after": true }],
				"@stylistic/semi-style": ["error", "last"],
				"@stylistic/space-before-blocks": ["error", "always"],
				"@stylistic/space-before-function-paren": ["error", { "anonymous": "always", "named": "never" }],
				"@stylistic/space-in-parens": ["error", "always", { "exceptions": ["empty"] }],
				"@stylistic/space-infix-ops": "error",
				"@stylistic/space-unary-ops": ["error", { "words": true, "nonwords": false }],
				"@stylistic/spaced-comment": ["error", "always", { "exceptions": ["*", "!"], "block": { "balanced": true } }],
				"@stylistic/switch-colon-spacing": ["error", { "after": true, "before": false }],
				"unicode-bom": "error",
				"@stylistic/wrap-iife": "error",
			"yoda": ["error", "never"],

			// Common extras
			"security/detect-object-injection": "off",
			"unicorn/prefer-date-now": "error",
			"unicorn/prefer-string-slice": "error",
			"unicorn/throw-new-error": "error",

			// Client-specific rules (browser environment)
			"no-alert": "error",
			//"no-console": "error",
			"no-implied-eval": "error",
			"unicorn/no-invalid-remove-event-listener": "error",
			"security/detect-non-literal-regexp": "off",
			"security/detect-unsafe-regex": "off",
			"security/detect-possible-timing-attacks": "off",

			// ES2017 language profile (stylistic via @stylistic)
			    "@stylistic/arrow-parens": "error",
			    "@stylistic/arrow-spacing": "error",
			"default-param-last": "error",
			    "@stylistic/lines-between-class-members": "error",
			"no-constructor-return": "error",
			"no-misleading-character-class": "error",
			"no-new-require": "error",
			"no-promise-executor-return": "error",
			"no-useless-computed-key": "error",
			    "@stylistic/template-curly-spacing": ["error", "always"],
			"no-var": "error",
			"prefer-const": "error",
			"prefer-arrow-callback": "error",
			    "@stylistic/implicit-arrow-linebreak": "error",
			    "arrow-body-style": "error",
			"unicorn/no-useless-promise-resolve-reject": "error",
			"unicorn/prefer-includes": "error",
			"es-x/no-restricted-syntax": "off",
			"es-x/no-symbol-prototype-description": "off",
			"es-x/no-resizable-and-growable-arraybuffers": "off",

			// ES2017 specific
			"no-await-in-loop": "error",
			"require-atomic-updates": "error"
		}
	},
	{
		name: "rater/json",
		files: ["**/*.json", "**/*.jsonc", "**/*.json5"],
		plugins: { json, security },
		language: "json/json",
		rules: {
			"json/no-duplicate-keys": "error",
			"indent": ["error", "tab"],
			"max-len": "off",
			"strict": "off",
			"security/detect-bidi-characters": "off"
		}
	},
	{
		name: "rater/markdown",
		files: ["**/*.md"],
		plugins: { markdown },
		language: "markdown/commonmark",
		rules: { "markdown/no-html": "error" }
	}
];
