// Services barrel export
export { default as API, makeErrorMsg } from './api.js';
export { default as windowManager } from './windowManager.js';
export { default as i18n } from './i18n.js';
export { default as cache } from './cache.js';
export { getBannerNames } from './collectBannersFromCategory.js';
export { default as setupRater } from './setup.js';
export { default as autostart } from './autostart.js';
export { default as prefs } from './prefs.js';
export { getPrediction as ores } from './ores.js';
export { getTemplateData } from './templateData.js';
export { buildBannerSuggestions, inferDefaults } from './autofill.js';
export { fetchTalkWikitext, fetchLatestRevId } from './pageContent.js';
export { checkSubjectFeatures } from './subjectPage.js';
export { applyBannerInsert } from './bannerApply.js';
export { parsePreview, compareDiff } from './preview.js';
export { isShellTemplate, getShellTemplateAliases, getShellTemplateAliasesSync } from './templateShell.js';
export { loadParamDataAndSuggestions } from './templateParams.js';
export { loadRatings } from './templateRatings.js';
export { getWithRedirectTo, resolveRedirects, getCanonicalName } from './templateRedirects.js';
