name: Deploy

on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Get tag message
      if: startsWith(github.ref, 'refs/tags/')
      id: tag_message
      run: |
        TAG_MESSAGE=$(git show --format='%B' --no-patch ${{ github.ref_name }})
        echo "tag_message<<EOF" >> $GITHUB_OUTPUT
        echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ${{ steps.tag_message.outputs.tag_message || format('Release {0}', github.ref_name) }}
          
          ## Build Artifacts
          - `dist/rater.js` - Loader script (unminified)
          - `dist/rater-core.js` - Main application bundle (minified)
          
          ## Installation
          Install the userscript by copying the contents of `dist/rater.js` into your userscript manager.
        files: |
          dist/rater.js
          dist/rater-core.js
